

services:
  postgres:
    image: postgres:15-alpine
    container_name: incorporflow_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data      
    networks:
      - incorporflow_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: incorporflow_backend
    environment:
      DOCKER_ENV: "true"
      DB_HOST_DOCKER: ${DB_HOST_DOCKER}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_DIALECT: ${DB_DIALECT}
      NODE_ENV: ${NODE_ENV}
      PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - incorporflow_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: incorporflow_frontend
    ports:
      - "${FRONTEND_PORT}:80"
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_PORT}
    depends_on:
      - backend
    networks:
      - incorporflow_network

networks:
  incorporflow_network:
    driver: bridge
